spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: project-service
          uri: lb://project-management-service
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=1
        - id: task-service
          uri: lb://task-management-service
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=1
        - id: resource-service
          uri: lb://resource-management-service
          predicates:
            - Path=/resources/**
          filters:
            - StripPrefix=1
  discovery:
    client:
      simple:
        enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

